OSMfile: osmData/TX-To-TU.osm
buildConnFile: buildingConnection.csv
buildingConfigPath: config/tsukuba-tu-building-data.csv
jobsFile: config/jobs.csv
numberOfAgents: 1000
threadNumber: 4
infectedAgent: 20
vaccinationPercentage: 0.0
verbose: false
gridHeight: 10
gridWidth: 10
windowWidth: 1024
windowHeight: 768
reportDir: report
reportInterval: 5
